// Mocks generated by Mockito 5.4.6 from annotations
// in peppercheck_flutter/test/features/auth/application/current_app_user_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:peppercheck_flutter/features/auth/data/me_repository.dart'
    as _i3;
import 'package:peppercheck_flutter/features/auth/domain/app_user.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppUser_0 extends _i1.SmartFake implements _i2.AppUser {
  _FakeAppUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeRepository extends _i1.Mock implements _i3.MeRepository {
  @override
  _i4.Future<_i2.AppUser> fetchMe() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMe, []),
            returnValue: _i4.Future<_i2.AppUser>.value(
              _FakeAppUser_0(this, Invocation.method(#fetchMe, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.AppUser>.value(
              _FakeAppUser_0(this, Invocation.method(#fetchMe, [])),
            ),
          )
          as _i4.Future<_i2.AppUser>);
}
