// Mocks generated by Mockito 5.4.6 from annotations
// in peppercheck_flutter/test/features/task/ui/task_detail_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:peppercheck_flutter/features/task/data/task_repository.dart'
    as _i3;
import 'package:peppercheck_flutter/features/task/domain/task.dart' as _i2;
import 'package:peppercheck_flutter/features/task/domain/task_creation_request.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  @override
  _i4.Future<_i2.Task> createDraft(_i5.TaskCreationRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createDraft, [request]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#createDraft, [request])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#createDraft, [request])),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<_i2.Task> updateDraft(
    String? id,
    _i5.TaskCreationRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDraft, [id, request]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#updateDraft, [id, request])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#updateDraft, [id, request])),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<void> deleteDraft(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDraft, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Task> publish(String? id, {required int? refereeCount}) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [id], {#refereeCount: refereeCount}),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_0(
                this,
                Invocation.method(
                  #publish,
                  [id],
                  {#refereeCount: refereeCount},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Task>.value(
              _FakeTask_0(
                this,
                Invocation.method(
                  #publish,
                  [id],
                  {#refereeCount: refereeCount},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<_i2.Task> getTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTask, [id]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#getTask, [id])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#getTask, [id])),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<List<_i2.Task>> fetchMyActiveTasks() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMyActiveTasks, []),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Task>>.value(
              <_i2.Task>[],
            ),
          )
          as _i4.Future<List<_i2.Task>>);
}
