// Mocks generated by Mockito 5.4.6 from annotations
// in peppercheck_flutter/test/features/task/ui/withdraw_button_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:peppercheck_flutter/features/matching/data/matching_repository.dart'
    as _i6;
import 'package:peppercheck_flutter/features/matching/domain/matching_config.dart'
    as _i2;
import 'package:peppercheck_flutter/features/matching/domain/referee_available_time_slot.dart'
    as _i4;
import 'package:peppercheck_flutter/features/matching/domain/referee_blocked_date.dart'
    as _i5;
import 'package:peppercheck_flutter/features/task/domain/task.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMatchingConfig_0 extends _i1.SmartFake
    implements _i2.MatchingConfig {
  _FakeMatchingConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTask_1 extends _i1.SmartFake implements _i3.Task {
  _FakeTask_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefereeAvailableTimeSlot_2 extends _i1.SmartFake
    implements _i4.RefereeAvailableTimeSlot {
  _FakeRefereeAvailableTimeSlot_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefereeBlockedDate_3 extends _i1.SmartFake
    implements _i5.RefereeBlockedDate {
  _FakeRefereeBlockedDate_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MatchingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchingRepository extends _i1.Mock
    implements _i6.MatchingRepository {
  @override
  _i7.Future<_i2.MatchingConfig> fetchConfig() =>
      (super.noSuchMethod(
            Invocation.method(#fetchConfig, []),
            returnValue: _i7.Future<_i2.MatchingConfig>.value(
              _FakeMatchingConfig_0(this, Invocation.method(#fetchConfig, [])),
            ),
            returnValueForMissingStub: _i7.Future<_i2.MatchingConfig>.value(
              _FakeMatchingConfig_0(this, Invocation.method(#fetchConfig, [])),
            ),
          )
          as _i7.Future<_i2.MatchingConfig>);

  @override
  _i7.Future<List<_i3.Task>> fetchMyAssignments() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMyAssignments, []),
            returnValue: _i7.Future<List<_i3.Task>>.value(<_i3.Task>[]),
            returnValueForMissingStub: _i7.Future<List<_i3.Task>>.value(
              <_i3.Task>[],
            ),
          )
          as _i7.Future<List<_i3.Task>>);

  @override
  _i7.Future<_i3.Task> cancelAssignment(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelAssignment, [requestId]),
            returnValue: _i7.Future<_i3.Task>.value(
              _FakeTask_1(
                this,
                Invocation.method(#cancelAssignment, [requestId]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.Task>.value(
              _FakeTask_1(
                this,
                Invocation.method(#cancelAssignment, [requestId]),
              ),
            ),
          )
          as _i7.Future<_i3.Task>);

  @override
  _i7.Future<List<_i4.RefereeAvailableTimeSlot>> fetchTimeSlots() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTimeSlots, []),
            returnValue: _i7.Future<List<_i4.RefereeAvailableTimeSlot>>.value(
              <_i4.RefereeAvailableTimeSlot>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i4.RefereeAvailableTimeSlot>>.value(
                  <_i4.RefereeAvailableTimeSlot>[],
                ),
          )
          as _i7.Future<List<_i4.RefereeAvailableTimeSlot>>);

  @override
  _i7.Future<_i4.RefereeAvailableTimeSlot> createTimeSlot({
    required int? dow,
    required int? startMin,
    required int? endMin,
    bool? isActive = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTimeSlot, [], {
              #dow: dow,
              #startMin: startMin,
              #endMin: endMin,
              #isActive: isActive,
            }),
            returnValue: _i7.Future<_i4.RefereeAvailableTimeSlot>.value(
              _FakeRefereeAvailableTimeSlot_2(
                this,
                Invocation.method(#createTimeSlot, [], {
                  #dow: dow,
                  #startMin: startMin,
                  #endMin: endMin,
                  #isActive: isActive,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i4.RefereeAvailableTimeSlot>.value(
                  _FakeRefereeAvailableTimeSlot_2(
                    this,
                    Invocation.method(#createTimeSlot, [], {
                      #dow: dow,
                      #startMin: startMin,
                      #endMin: endMin,
                      #isActive: isActive,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i4.RefereeAvailableTimeSlot>);

  @override
  _i7.Future<void> updateTimeSlot({
    required String? id,
    required int? dow,
    required int? startMin,
    required int? endMin,
    required bool? isActive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTimeSlot, [], {
              #id: id,
              #dow: dow,
              #startMin: startMin,
              #endMin: endMin,
              #isActive: isActive,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteTimeSlot(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTimeSlot, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.RefereeBlockedDate>> fetchBlockedDates() =>
      (super.noSuchMethod(
            Invocation.method(#fetchBlockedDates, []),
            returnValue: _i7.Future<List<_i5.RefereeBlockedDate>>.value(
              <_i5.RefereeBlockedDate>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i5.RefereeBlockedDate>>.value(
                  <_i5.RefereeBlockedDate>[],
                ),
          )
          as _i7.Future<List<_i5.RefereeBlockedDate>>);

  @override
  _i7.Future<_i5.RefereeBlockedDate> createBlockedDate({
    required DateTime? startDate,
    required DateTime? endDate,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBlockedDate, [], {
              #startDate: startDate,
              #endDate: endDate,
              #reason: reason,
            }),
            returnValue: _i7.Future<_i5.RefereeBlockedDate>.value(
              _FakeRefereeBlockedDate_3(
                this,
                Invocation.method(#createBlockedDate, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                  #reason: reason,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.RefereeBlockedDate>.value(
              _FakeRefereeBlockedDate_3(
                this,
                Invocation.method(#createBlockedDate, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                  #reason: reason,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.RefereeBlockedDate>);

  @override
  _i7.Future<void> updateBlockedDate({
    required String? id,
    required DateTime? startDate,
    required DateTime? endDate,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBlockedDate, [], {
              #id: id,
              #startDate: startDate,
              #endDate: endDate,
              #reason: reason,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteBlockedDate(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBlockedDate, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
