// Mocks generated by Mockito 5.4.6 from annotations
// in peppercheck_flutter/test/features/profile/ui/timezone_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:logger/src/log_level.dart' as _i7;
import 'package:logger/src/logger.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:peppercheck_flutter/features/profile/data/avatar_upload_dto.dart'
    as _i3;
import 'package:peppercheck_flutter/features/profile/data/profile_repository.dart'
    as _i4;
import 'package:peppercheck_flutter/features/profile/domain/profile.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfile_0 extends _i1.SmartFake implements _i2.Profile {
  _FakeProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAvatarUploadDto_1 extends _i1.SmartFake
    implements _i3.AvatarUploadDto {
  _FakeAvatarUploadDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i4.ProfileRepository {
  @override
  _i5.Future<_i2.Profile> fetchOwn() =>
      (super.noSuchMethod(
            Invocation.method(#fetchOwn, []),
            returnValue: _i5.Future<_i2.Profile>.value(
              _FakeProfile_0(this, Invocation.method(#fetchOwn, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Profile>.value(
              _FakeProfile_0(this, Invocation.method(#fetchOwn, [])),
            ),
          )
          as _i5.Future<_i2.Profile>);

  @override
  _i5.Future<void> updateUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#updateUsername, [username]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateTimezone(String? timezone) =>
      (super.noSuchMethod(
            Invocation.method(#updateTimezone, [timezone]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.AvatarUploadDto> requestAvatarUpload({
    required String? contentType,
    required int? fileSizeBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestAvatarUpload, [], {
              #contentType: contentType,
              #fileSizeBytes: fileSizeBytes,
            }),
            returnValue: _i5.Future<_i3.AvatarUploadDto>.value(
              _FakeAvatarUploadDto_1(
                this,
                Invocation.method(#requestAvatarUpload, [], {
                  #contentType: contentType,
                  #fileSizeBytes: fileSizeBytes,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.AvatarUploadDto>.value(
              _FakeAvatarUploadDto_1(
                this,
                Invocation.method(#requestAvatarUpload, [], {
                  #contentType: contentType,
                  #fileSizeBytes: fileSizeBytes,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AvatarUploadDto>);

  @override
  _i5.Future<void> commitAvatar(String? publicUrl) =>
      (super.noSuchMethod(
            Invocation.method(#commitAvatar, [publicUrl]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i6.Logger {
  @override
  _i5.Future<void> get init =>
      (super.noSuchMethod(
            Invocation.getter(#init),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void v(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #v,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void t(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #t,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void d(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #d,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void i(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #i,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void w(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #w,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void e(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #e,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void wtf(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #wtf,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void f(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #f,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void log(
    _i7.Level? level,
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #log,
      [level, message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool isClosed() =>
      (super.noSuchMethod(
            Invocation.method(#isClosed, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
