name: "🐛 Bug report"
description: Report a problem
labels: ["type/bug", "status/triage"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Affected area (labels to apply)
      options:
        - area/android
        - area/supabase
        - area/cloudflare
        - area/web
        - area/backend
        - area/infra
      multiple: true
      description: Select one or more areas. These will be applied as labels by a workflow.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / Build info
      placeholder: e.g., Android 15, commit 1a2b3c, prod
  - type: textarea
    id: desc
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      render: shell
  - type: dropdown
    id: priority
    attributes:
      label: Priority (label to apply)
      options:
        - priority/P0
        - priority/P1
        - priority/P2
        - priority/P3
      description: If omitted, P2 will be set by a workflow.

