name: "🔬 Spike / Research"
description: Time-boxed investigation
labels: ["type/spike", "status/triage"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area (labels to apply)
      options:
        - area/android
        - area/supabase
        - area/cloudflare
        - area/web
        - area/backend
        - area/infra
      multiple: true
  - type: textarea
    id: goal
    attributes:
      label: Goal / Hypothesis
    validations:
      required: true
  - type: input
    id: timebox
    attributes:
      label: Timebox
      placeholder: e.g., 0.5d, 1d, 2d

