// Mocks generated by Mockito 5.4.6 from annotations
// in peppercheck_flutter/test/features/home/ui/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:peppercheck_flutter/features/matching/data/matching_repository.dart'
    as _i7;
import 'package:peppercheck_flutter/features/matching/domain/matching_config.dart'
    as _i3;
import 'package:peppercheck_flutter/features/matching/domain/referee_available_time_slot.dart'
    as _i8;
import 'package:peppercheck_flutter/features/matching/domain/referee_blocked_date.dart'
    as _i10;
import 'package:peppercheck_flutter/features/task/data/task_repository.dart'
    as _i4;
import 'package:peppercheck_flutter/features/task/domain/task.dart' as _i2;
import 'package:peppercheck_flutter/features/task/domain/task_creation_request.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMatchingConfig_1 extends _i1.SmartFake
    implements _i3.MatchingConfig {
  _FakeMatchingConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i4.TaskRepository {
  @override
  _i5.Future<_i2.Task> createDraft(_i6.TaskCreationRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createDraft, [request]),
            returnValue: _i5.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#createDraft, [request])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#createDraft, [request])),
            ),
          )
          as _i5.Future<_i2.Task>);

  @override
  _i5.Future<_i2.Task> updateDraft(
    String? id,
    _i6.TaskCreationRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDraft, [id, request]),
            returnValue: _i5.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#updateDraft, [id, request])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#updateDraft, [id, request])),
            ),
          )
          as _i5.Future<_i2.Task>);

  @override
  _i5.Future<void> deleteDraft(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDraft, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Task> publish(String? id, {required int? refereeCount}) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [id], {#refereeCount: refereeCount}),
            returnValue: _i5.Future<_i2.Task>.value(
              _FakeTask_0(
                this,
                Invocation.method(
                  #publish,
                  [id],
                  {#refereeCount: refereeCount},
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Task>.value(
              _FakeTask_0(
                this,
                Invocation.method(
                  #publish,
                  [id],
                  {#refereeCount: refereeCount},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Task>);

  @override
  _i5.Future<_i2.Task> getTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTask, [id]),
            returnValue: _i5.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#getTask, [id])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#getTask, [id])),
            ),
          )
          as _i5.Future<_i2.Task>);

  @override
  _i5.Future<List<_i2.Task>> fetchMyActiveTasks() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMyActiveTasks, []),
            returnValue: _i5.Future<List<_i2.Task>>.value(<_i2.Task>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Task>>.value(
              <_i2.Task>[],
            ),
          )
          as _i5.Future<List<_i2.Task>>);
}

/// A class which mocks [MatchingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchingRepository extends _i1.Mock
    implements _i7.MatchingRepository {
  @override
  _i5.Future<_i3.MatchingConfig> fetchConfig() =>
      (super.noSuchMethod(
            Invocation.method(#fetchConfig, []),
            returnValue: _i5.Future<_i3.MatchingConfig>.value(
              _FakeMatchingConfig_1(this, Invocation.method(#fetchConfig, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.MatchingConfig>.value(
              _FakeMatchingConfig_1(this, Invocation.method(#fetchConfig, [])),
            ),
          )
          as _i5.Future<_i3.MatchingConfig>);

  @override
  _i5.Future<List<_i2.Task>> fetchMyAssignments() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMyAssignments, []),
            returnValue: _i5.Future<List<_i2.Task>>.value(<_i2.Task>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Task>>.value(
              <_i2.Task>[],
            ),
          )
          as _i5.Future<List<_i2.Task>>);

  @override
  _i5.Future<_i2.Task> cancelAssignment(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelAssignment, [requestId]),
            returnValue: _i5.Future<_i2.Task>.value(
              _FakeTask_0(
                this,
                Invocation.method(#cancelAssignment, [requestId]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Task>.value(
              _FakeTask_0(
                this,
                Invocation.method(#cancelAssignment, [requestId]),
              ),
            ),
          )
          as _i5.Future<_i2.Task>);

  @override
  _i5.Future<List<_i8.RefereeAvailableTimeSlot>> getRefereeAvailableTimeSlots(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRefereeAvailableTimeSlots, [userId]),
            returnValue: _i5.Future<List<_i8.RefereeAvailableTimeSlot>>.value(
              <_i8.RefereeAvailableTimeSlot>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i8.RefereeAvailableTimeSlot>>.value(
                  <_i8.RefereeAvailableTimeSlot>[],
                ),
          )
          as _i5.Future<List<_i8.RefereeAvailableTimeSlot>>);

  @override
  _i5.Future<String> createRefereeAvailableTimeSlot({
    required int? dow,
    required int? startMin,
    required int? endMin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRefereeAvailableTimeSlot, [], {
              #dow: dow,
              #startMin: startMin,
              #endMin: endMin,
            }),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#createRefereeAvailableTimeSlot, [], {
                  #dow: dow,
                  #startMin: startMin,
                  #endMin: endMin,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#createRefereeAvailableTimeSlot, [], {
                  #dow: dow,
                  #startMin: startMin,
                  #endMin: endMin,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> updateRefereeAvailableTimeSlot({
    required String? id,
    required int? dow,
    required int? startMin,
    required int? endMin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRefereeAvailableTimeSlot, [], {
              #id: id,
              #dow: dow,
              #startMin: startMin,
              #endMin: endMin,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteRefereeAvailableTimeSlot(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefereeAvailableTimeSlot, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i10.RefereeBlockedDate>> getRefereeBlockedDates() =>
      (super.noSuchMethod(
            Invocation.method(#getRefereeBlockedDates, []),
            returnValue: _i5.Future<List<_i10.RefereeBlockedDate>>.value(
              <_i10.RefereeBlockedDate>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i10.RefereeBlockedDate>>.value(
                  <_i10.RefereeBlockedDate>[],
                ),
          )
          as _i5.Future<List<_i10.RefereeBlockedDate>>);

  @override
  _i5.Future<String> createRefereeBlockedDate({
    required DateTime? startDate,
    required DateTime? endDate,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRefereeBlockedDate, [], {
              #startDate: startDate,
              #endDate: endDate,
              #reason: reason,
            }),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#createRefereeBlockedDate, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                  #reason: reason,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#createRefereeBlockedDate, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                  #reason: reason,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> updateRefereeBlockedDate({
    required String? id,
    required DateTime? startDate,
    required DateTime? endDate,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRefereeBlockedDate, [], {
              #id: id,
              #startDate: startDate,
              #endDate: endDate,
              #reason: reason,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteRefereeBlockedDate(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefereeBlockedDate, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
