targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: ja
          fallback_strategy: base_locale
          input_directory: assets/i18n
          output_directory: lib/gen/slang
          output_file_name: strings.g.dart
